role_id: documentation_reviewer
role_name: "Documentation Reviewer"
trigger_labels:
  - req_start_documentation_reviewer
status_labels:
  done: done_documentation_reviewer
  accept: accept_documentation_reviewer
  reject: reject_documentation_reviewer
