role_id: developer_impl
role_name: "Developer Implementation"
trigger_labels:
  - req_start_developer_impl
status_labels:
  done: done_developer_impl
  accept: accept_developer_impl
  reject: reject_developer_impl
