role_id: documentation_developer
role_name: "Documentation Developer"
trigger_labels:
  - req_start_documentation_developer
status_labels:
  done: done_documentation_developer
  accept: accept_documentation_developer
  reject: reject_documentation_developer
